// app-vue/src/components/shell/GlobalSearch.vue
<template>
  <div class="relative">
    <button
      type="button"
      class="flex items-center gap-2 px-3 py-1.5 rounded-md bg-white/5 text-slate-400 hover:text-slate-200 text-sm"
      @click="open = !open"
    >
      <span class="opacity-80">⌘K</span>
      <span>Search</span>
    </button>
    <template v-if="open">
      <div class="fixed inset-0 z-40" aria-hidden @click="open = false" />
      <div
        class="absolute right-0 top-full mt-1 z-50 w-96 rounded-lg border border-cordros-slate bg-cordros-navy shadow-xl p-2"
      >
        <input
          v-model="query"
          type="text"
          placeholder="Search deals, documents, entities…"
          class="w-full px-3 py-2 rounded bg-cordros-slate/50 border border-cordros-slate text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-cordros-accent"
          autofocus
        />
        <p class="mt-2 text-xs text-slate-500">Unified search across Data Fabric (role-scoped).</p>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const open = ref(false);
const query = ref("");
</script>

// src/components/shell/GlobalSearch.tsx
import { useEffect } from "react";
import { Search } from "lucide-react";
import { cn } from "@/lib/cn";

interface GlobalSearchProps {
  onOpen: () => void;
  className?: string;
}

export function GlobalSearch({ onOpen, className }: GlobalSearchProps) {
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        onOpen();
      }
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [onOpen]);

  return (
    <button
      type="button"
      onClick={onOpen}
      className={cn(
        "flex items-center gap-2.5 rounded-xl border border-white/10 bg-white/[0.03] px-3.5 py-2 text-sm text-cordros-textSecondary transition-all",
        "hover:border-white/15 hover:bg-white/[0.05] hover:text-cordros-text",
        "focus:outline-none focus:ring-2 focus:ring-cordros-accent/30 focus:ring-offset-2 focus:ring-offset-cordros-bg",
        className
      )}
    >
      <Search className="h-4 w-4 shrink-0 text-cordros-textTertiary" strokeWidth={2} />
      <span>Search</span>
      <kbd className="ml-1 hidden rounded bg-white/10 px-1.5 py-0.5 font-mono text-[10px] sm:inline">
        ⌘K
      </kbd>
    </button>
  );
}
